---
core:
  step: preprocess-sites
  pipeline: Pooled Cell Painting
  project: 2018_11_20_Periscope_Calico
  batch: 20190919_6W_CP074A
  project_dir: /Users/gway/work/projects/2018_11_20_Periscope_Calico
  data_dir: /workspace/analysis/20190919_6W_CP074A
  output_dir: data
  categorize_cells: simple
  compartments:
    - Cells
    - Nuclei
    - Cytoplasm
  parent_cols:
    cells:
      - Parent_Nuclei
    cytoplasm:
      - Parent_Nuclei
      - Parent_Cells
  id_cols:
    - ImageNumber
    - ObjectNumber
---
prefilter:
  perform: true
  example_site: CP074A_A1-Site_1
  output_dir: data
  flag_cols:
    - Barcode
    - Location
    - Count
---
process-foci:
  perform: true
  barcode_col: Barcode_MatchedTo_Barcode
  gene_col: Barcode_MatchedTo_GeneCode
  location_cols:
    - Location_Center_X
    - Location_Center_Y
  foci_cols:
    - Barcode_BarcodeCalled
    - Barcode_MatchedTo_ID
    - Barcode_MatchedTo_Score
---
process-cells:
  perform: true
  sort_col: Metadata_Cells_ObjectNumber
