---
core:
  step: preprocess-sites
  pipeline: Pooled Cell Painting
  project: 2018_11_20_Periscope_Calico
  batch: 20190919_6W_CP074A
  project_dir: /Users/gway/work/projects/
  output_dir: data
  categorize_cell_quality: simple
  compartments:
    - Cells
    - Nuclei
    - Cytoplasm
  parent_cols:
    cells:
      - Parent_Nuclei
    cytoplasm:
      - Parent_Nuclei
      - Parent_Cells
    spots:
      - Parent_Cells
  id_cols:
    - ImageNumber
    - ObjectNumber
  control_barcodes:
    - NT
  trash_files:
    - .DS_Store
---
prefilter:
  perform: true
  example_site: CP074A_A1-Site_1
  output_basedir: data
  flag_cols:
    - Barcode
    - Location
    - Count
    - Resize
---
process-spots:
  perform: true
  output_basedir: data
  barcode_cols:
    - Barcode_MatchedTo_Barcode
  gene_cols:
    - Barcode_MatchedTo_GeneCode
  location_cols:
    - Location_Center_X
    - Location_Center_Y
  spot_score_cols:
    - Barcode_MatchedTo_Score
  foci_cols:
    - Barcode_BarcodeCalled
    - Barcode_MatchedTo_ID
  cell_filter:
    - Perfect
    - Great
---
process-cells:
  perform: true
  prefilter-features: true
  output_basedir: data
  sort_col: Metadata_Cells_ObjectNumber
